# libtzsolar-boost Makefile

# first target is default build targer
.PHONY: all
all: libtzsolar-boost.o

# get common make rules
include ../common.mk

# local settings - either overriding or in addition to common make rules

# file lists
CLEAN_FILES = libtzsolar-boost.o
SPOTLESS_FILES =

