---
name: Perl
# yamllint disable rule:line-length
on:  # yamllint disable-line rule:truthy
  push:
    paths: ['src/perl/**', '.github/workflows/test-perl.yml']
  pull_request:
    paths: ['src/perl/**', '.github/workflows/test-perl.yml']
  workflow_dispatch:
  # schedule:
  #   - cron: '42 5 * * *'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        perl: ['5.20', '5.30', '5.40', '5.42']
        exclude:
          - {runner: "windows-latest", perl: '5.20'}
          - {runner: "windows-latest", perl: '5.30'}
    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ ( startsWith( matrix.runner, 'windows-' ) && 'strawberry' ) || 'default' }}
          install-modules-with: cpanm
          install-modules: Dist::Zilla Test::Pod Pod::Markdown IPC::Run File::Slurp
      - name: Show Perl Version
        run: |
          perl -v
          cpanm -v
          dzil --version
      - name: Install Modules
        run: |
          cd src/perl
          dzil authordeps --missing | cpanm --notest
          dzil listdeps --develop --missing | cpanm --notest
      - name: Show Errors on Windows
        if: ${{ failure() && startsWith( matrix.runner, 'windows-')}}
        run: |
           ls -l C:/Users/
           ls -l C:/Users/RUNNER~1/
           cat C:/Users/runneradmin/.cpanm/work/*/build.log
      - name: Show Errors on Ubuntu
        if: ${{ failure() && startsWith( matrix.runner, 'ubuntu-')}}
        run: |
           cat /home/runner/.cpanm/work/*/build.log
      - name: Show Errors on OSX
        if: ${{ failure() && startsWith( matrix.runner, 'macos-')}}
        run: |
           cat  /Users/runner/.cpanm/work/*/build.log
      - name: Run Perl tests
        run: |
          cd src/perl
          dzil test --release
          dzil install
      - name: Run black box tests
        run: |
          prove test/cli-test-perl.t
