---
name: Python
# yamllint disable rule:line-length
on:  # yamllint disable-line rule:truthy
  push:
    paths: ['src/python/**', '.github/workflows/test-python.yml']
  pull_request:
    paths: ['src/python/**', '.github/workflows/test-python.yml']
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # runner: [ubuntu-latest, macos-latest, windows-latest]
        runner: [ubuntu-latest]
        python-version: ['3.11']
    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Python ${{matrix.python-version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
          cache: 'pip'
      - name: Install dependencies
        run: |
          export PYTHONPATH=$PWD/src/python
          cd src/python/timezone_solar
          pip install -r requirements.txt
      - name: Run flake8
        run: |
          export PYTHONPATH=$PWD/src/python
          cd src/python/timezone_solar
          flake8 *.py test/*.py
      - name: Run unit tests
        run: |
          export PYTHONPATH=$PWD/src/python
          cd src/python/timezone_solar
          python test --tapview
