---
name: Python
# yamllint disable rule:line-length
on:  # yamllint disable-line rule:truthy
  push:
    paths: ['src/python/**', '.github/workflows/test-python.yml']
  pull_request:
    paths: ['src/python/**', '.github/workflows/test-python.yml']
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Python ${{matrix.python-version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
          cache: 'pip'
      - name: Set Python path on Windows
        if: startsWith( matrix.runner, 'windows-')}}
            echo "PYTHONPATH=${{env.GITHUB_WORKSPACE}}\src\python" >> $GITHUB_ENV
      - name: Set Python path on Linux & MacOS
        if: startsWith( matrix.runner, 'ubuntu-')}} || startsWith( matrix.runner, 'macos-')}}
            echo "PYTHONPATH=${{env.GITHUB_WORKSPACE}}/src/python" >> $GITHUB_ENV
      - name: Install dependencies
        working-directory: src/python/timezone_solar
        run: |
          pip install -r requirements.txt
      - name: Run flake8
        working-directory: src/python/timezone_solar
        run: |
          flake8 *.py test/*.py
      - name: Run tests
        working-directory: src/python/timezone_solar
        run: |
          python test --tapview
